name: CI/CD for Calculator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up dependencies (CMake, g++, and Google Test)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ 

      # Step 3: Download and build Google Test
      - name: Install Google Test
        run: |
          mkdir -p third_party
          cd third_party
          git clone https://github.com/google/googletest.git
          cd googletest
          mkdir -p build
          cd build
          cmake ..
          make
          sudo make install

      # Step 4: Build the Project with CMake
      - name: Build Project
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      # Step 5: Run Tests
      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure
