name: CI/CD for Calculator

# Run the workflow on pushes to main branch and pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up C++ compiler
      - name: Set up C++ compiler
        run: sudo apt-get update && sudo apt-get install -y g++

      # Step 3: Compile calculator.cpp and test_calculator.cpp
      - name: Compile Calculator
        run: |
          g++ -o calculator calculator.cpp test_calculator.cpp -lgtest -lgtest_main -pthread

      # Step 4: Run tests
      - name: Run Tests
        run: ./calculator
