name: CI/CD for Calculator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up dependencies (CMake, Google Test)
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++

      # Step 3: Build with CMake
      - name: Build Project
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      # Step 4: Run tests
      - name: Run Tests
        run: |
          cd build
          ctest --output-on-failure
